LojaQuadrinhos.WebApp/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using LojaQuadrinhos.Model.Dtos;
using LojaQuadrinhos.Business;
using LojaQuadrinhos.Data;
using LojaQuadrinhos.WebApp.Data;

namespace LojaQuadrinhos.WebApp.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly CategoriaBusiness _categoriaBusiness;
        private UnitOfWork unitOfWork;

        public CategoriasController(LojaQuadrinhosContext context)
        {
            unitOfWork = new UnitOfWork(context);
            _categoriaBusiness = new CategoriaBusiness(unitOfWork);
        }

        public IActionResult Index()
        {
            return View(_categoriaBusiness.ListarTodos());
        }

        public IActionResult Criar(int id)
        {
            if(id > 0)
            {
                var categoriaDto = _categoriaBusiness.BuscarPorId(id);
                if (categoriaDto == null)
                {
                    return NotFound();
                }
                return View(categoriaDto);
            }
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Criar")]
        public IActionResult Salvar(int id, [Bind("ID,Descricao")] CategoriaDto categoriaDto)
        {

            if (ModelState.IsValid)
            {
                _categoriaBusiness.Salvar(categoriaDto);

                return RedirectToAction(nameof(Index));
            }
            return View(categoriaDto);
        }

        public IActionResult Excluir(int id)
        {
            CategoriaDto categoriaDto = _categoriaBusiness.BuscarPorId(id);
            if (categoriaDto == null)
            {
                return NotFound();
            }
            return View(categoriaDto);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public IActionResult ExcluirConfirma(int id)
        {

            bool retorno = _categoriaBusiness.Excluir(id);

            if (retorno)
                return RedirectToAction(nameof(Index));

            ModelState.AddModelError("Categoria", "Não é possível excluir categoria, pois ela esta vinculada a um produto");
            return View();

        }

    }
}

LojaQuadrinhos.WebApp/Controllers/PedidosController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using LojaQuadrinhos.WebApp.Data;
using LojaQuadrinhos.Model.Dtos;
using LojaQuadrinhos.Business;
using LojaQuadrinhos.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Security.Claims;
using System;


namespace LojaQuadrinhos.WebApp.Controllers
{
    public class PedidosController : Controller
    {
        private readonly PedidoBusiness _pedidoBusiness;
        private UnitOfWork unitOfWork;
        private readonly LojaQuadrinhosContext _context;

        public PedidosController(LojaQuadrinhosContext context)
        {
            _context = context;
            unitOfWork = new UnitOfWork(context);
            _pedidoBusiness = new PedidoBusiness(unitOfWork);
        }

        public IActionResult Index()
        {
            return View(_pedidoBusiness.ListarTodos());
        }
        public IActionResult Criar()
        {
            var userName = User.FindFirstValue(ClaimTypes.Name);
            PedidoDto pedidoDto = new PedidoDto()
            {
                Usuario = userName,
                DataDoPedido = DateTime.Now.Date,
                Quantidade = 1,
                PedidoProdutosDto = new List<PedidoProdutoDto>(),
            };
            ViewData["Produtos"] = new SelectList(CarregarProdutosAtivos(), "ProdutoId", "Titulo", false);

            return View(pedidoDto);
        }

        [HttpPost, ActionName("Criar")]
        [ValidateAntiForgeryToken]
        public IActionResult Salvar([Bind("ID,Usuario,DataDoPedido,ValorTotal,Quantidade,ProdutoId,PedidoProdutosDto")] PedidoDto pedido)
        {
            if (ModelState.IsValid)
            {
                _pedidoBusiness.Salvar(pedido);

                return RedirectToAction(nameof(Index));
            }
            ViewData["Produtos"] = new SelectList(CarregarProdutosAtivos(), "ProdutoId", "Titulo", false);

            return View(pedido);
        }

        [HttpPost]
        public IActionResult AdicionarProdutoAoPedido([Bind("ID,Usuario,DataDoPedido,ValorTotal,Quantidade,ProdutoId,PedidoProdutosDto")] PedidoDto pedido)
        {
            ViewData["Produtos"] = new SelectList(CarregarProdutosAtivos(), "ProdutoId", "Titulo", false);

            if (pedido.PedidoProdutosDto is null)
            {
                pedido.PedidoProdutosDto = new List<PedidoProdutoDto>();
            }
            
            var retorno = _pedidoBusiness.BuscarProdutoDoPedido(pedido);

            if (pedido.Sucesso)
            {
                ModelState.Clear();

                retorno.Quantidade = 1;
                return View("Criar", retorno);
            }
            else
            {
                ModelState.AddModelError("Produto", "O item selecionado possui apenas " + retorno.QtdDisponivelEstoque + " disponível");
                return View("Criar", pedido);             
            }

        }

        public IActionResult ExcluirProdutoDoPedido([Bind("ID,ValorTotal,QuantidadeDoPedido,Preco,PedidoProdutosDto")] int id, PedidoDto pedido)
        {
            ViewData["Produtos"] = new SelectList(CarregarProdutosAtivos(), "ProdutoId", "Titulo", false);
            ModelState.Clear();
            var pedidoProduto = pedido.PedidoProdutosDto.First(x => x.ProdutoID == id);
            pedido.PedidoProdutosDto.Remove(pedidoProduto);
            pedido.ValorTotal += -pedidoProduto.PrecoTotal;
            return View("Criar", pedido);
        }

        public IActionResult DetalhesProduto(int id)
        {
            ProdutoDto produtoDto = _pedidoBusiness.BuscarPoduto(id);
            if (produtoDto == null)
            {
                return NotFound();
            }
            return View(produtoDto);
        }

        public IActionResult Detalhes(int id)
        {
            PedidoDto pedidoDto = _pedidoBusiness.BuscarPorId(id);
            if (pedidoDto == null)
            {
                return NotFound();
            }
            return View(pedidoDto);
        }
        public IActionResult Excluir(int id)
        {
            PedidoDto pedidoDto = _pedidoBusiness.BuscarPorId(id);
            if (pedidoDto == null)
            {
                return NotFound();
            }

            return View(pedidoDto);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public IActionResult ExcluirConfirma(int id)
        {
            _pedidoBusiness.Excluir(id);
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedidos.Any(e => e.ID == id);
        }

        /// Carrega lista de produtos que tem estoque no Dropdow       
        private IEnumerable<ProdutosListaDto> CarregarProdutosAtivos()
        {
            return _pedidoBusiness.BuscarProdutos().ToList();
        }



    }
}

LojaQuadrinhos.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Loja de Quadrinhos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Loja de Quadrinhos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav ml-auto">
                        @*Se o usuário esta logado exibir o link de logout*@
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-controller="account" asp-action="logout">
                                    <button type="submit" style="width:auto"
                                            class="nav-link btn btn-link py-0">
                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="register">
                                    Registrar
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="account" asp-action="login">
                                    Login
                                </a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Index">Pedidos</a>
                            </li>
                        }

                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Loja de Quadrinhos
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

    <script src="~/Scripts/globalize/globalize.js"></script>
    <script src="~/Scripts/globalize/cultures/globalize.culture.pt-BR.js"></script>

    <script>

        $.validator.methods.number = function (value, element) {
            var val = Globalize.parseFloat(value);
            return this.optional(element) ||
                (val);
        }

        $.validator.methods.date = function (value, element) {
            var val = Globalize.parseDate(value);
            return this.optional(element) ||
                (val);
        }

        $(function () {

            Globalize.culture('pt-BR');

            jQuery.extend(jQuery.validator.methods, {
                range: function (value, element, param) {
                    //Use the Globalization plugin to parse the value
                    var val = Globalize.parseFloat(value);
                    return this.optional(element) || (
                        val >= param[0] && val <= param[1]);
                }
            });

        });
    </script>
</body>
</html>